### PR TITLE
420/388/430 - fix: replace NFTModel

### LINKED ISSUE #420: Replace NFTSendData with NFTModel

### LINKED ISSUE #430: [BUG] nft image is missing in send nft page
Image

### PR DESCRIPTION
**Pull request by lealobanov**
Closes #430, Closes #420, Closes https://github.com/onflow/FRW-monorepo/issues/388

## 🔗 Related Issues

Closes #420

https://github.com/user-attachments/assets/cfae4343-aae1-48b4-a0c9-7bac6edf15a2

Linked automatically from the branch name. If incorrect, edit:

### CODE REVIEW

File: packages/ui/src/components/ConfirmationDrawer.tsx [hunk 1]
```diff
@@ -8,15 +13,17 @@ import { AddressText } from './AddressText';
...
-import { type NFTSendData } from './NFTSendPreview';
 import { type TransactionFormData } from './TransactionConfirmationModal';
 import { Avatar } from '../foundation/Avatar';
 import { Text } from '../foundation/Text';
 export interface ConfirmationDrawerProps {
   visible: boolean;
   transactionType: TransactionType;
   selectedToken?: TokenModel | null;
-  selectedNFTs?: NFTSendData[];
+  selectedNFTs?: (NFTModel & {
```
Comment (lmcmz) [inline packages/ui/src/components/ConfirmationDrawer.tsx:23]: emmm.... I don't like this way to pass the data, I think we could add `selectedQuantity` as optional field in NFTModel or we can use `extend` type instead, or create a type with alias.

https://graphite.dev/guides/extending-types-typescript

File: packages/ui/src/components/MultipleNFTsPreview.tsx [hunk 2]
```diff
@@ -1,13 +1,16 @@
...
 import { YStack, XStack, ScrollView, Image, View, useTheme } from 'tamagui';
 
-import { type NFTSendData } from './NFTSendPreview';
 import { Text } from '../foundation/Text';
 
 export interface MultipleNFTsPreviewProps {
-  nfts: NFTSendData[];
+  nfts: (NFTModel & {
+    selectedQuantity?: number;
+    collection?: string;
```
Comment (lmcmz) [inline packages/ui/src/components/MultipleNFTsPreview.tsx:12]: I think the NFTModel itself, already have the collection data including, contractName, address, name and logo. What is this `collection?: string` for ?

**Review by lmcmz — CHANGES_REQUESTED** [review]

File: packages/types/src/Transaction.ts [hunk 3]
```diff
@@ -0,0 +1,43 @@
+/**
+ * Transaction-related type definitions for FRW
+ */
+
+/**
+ * Form data for transaction confirmation
+ */
+export interface TransactionFormData {
```
Comment (lmcmz) [inline packages/types/src/Transaction.ts:8]: I think we already the form payload data model

File: packages/types/src/Transaction.ts [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+  fiatAmount: string;
+  isTokenMode: boolean;
+  transactionFee?: string;
+}
+
+/**
+ * NFT with selected quantity for transactions
+ */
+export interface NFTWithQuantity {
+  id: string;
```
Comment (lmcmz) [inline packages/types/src/Transaction.ts:19]: we should reuse as what we have on the NFTModel as for the NFT Quantity, it should stay with the tx payload

File: packages/types/src/Transaction.ts [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+  evmAddress?: string;
+  address?: string;
+  selectedQuantity?: number;
+}
+
+/**
+ * Generic Token interface for UI components
+ */
+export interface Token {
+  symbol?: string;
```
Comment (lmcmz) [inline packages/types/src/Transaction.ts:36]: Same here, I do think we already have TokenModel, no need to create new one

**Review by lmcmz — APPROVED** [review]
