### PR TITLE
fix: update flowidentifier check and make confirmation scrollable whe…

### LINKED ISSUE #1034: [BUG] Failed to send wBTC from COA to EOA account

### PR DESCRIPTION
**Pull request by zzggo**
…n checking cadence script

Closes #1034

## 🔗 Related Issues

Linked automatically from the branch name. If incorrect, edit:

### CODE REVIEW

File: packages/utils/src/token.ts [hunk 1]
```diff
@@ -53,6 +54,10 @@ export function getTokenResourceIdentifier(token: TokenModel | null): string | n
   if (!token || !token.contractAddress || !token.contractName) {
     return null;
   }
+  // Only generate identifier for Flow addresses
+  if (!isValidFlowAddress(token.contractAddress)) {
```
Comment (lmcmz) [inline packages/utils/src/token.ts]: Are you sure this will fix the issue ? The current flow is we are getting the null or '' for identifier.
I think you need make change checks on the send workflow

Comment (zzggo) [reply packages/utils/src/token.ts]: The current issue is we are creating wrong identifier for evm token. This didn't pass the check. A.717dae2baf7656be9a9b01dee31d571a9d4c9579.Wrapped BTC.Vault. If the identifier is null it will not check the identifier

**Review by lmcmz — APPROVED** [review]
LGTM
