### PR TITLE
feat: fix parseunit round up issues

### LINKED ISSUE #1307: fix parseFloat issues

### PR DESCRIPTION
**Pull request by caosbad**
Closes #1307

## 🔗 Related Issues

Linked automatically from the branch name. If incorrect, edit:

## Self-Checklist

- [ ] I read through my own diff
- [ ] I ran at least one manual check
- [ ] No mock / debug code left in production code

### CODE REVIEW

File: packages/workflow/src/send/utils.ts [hunk 1]
```diff
@@ -108,16 +108,29 @@ export const getFlowTokenVault = (network: 'mainnet' | 'testnet'): string => {
...
-  if (isNaN(numAmount)) {
+  if (isNaN(Number(strAmount))) {
     throw new Error('Invalid number for UFix64 conversion');
   }
 
-  // Use toFixed(8) to ensure exactly 8 decimal places
-  return numAmount.toFixed(8);
+  // Expand scientific notation (e.g. 1e-7 → "0.0000001")
+  if (/[eE]/.test(strAmount)) {
+    strAmount = Number(strAmount).toFixed(20);
```
Comment (lmcmz) [inline packages/workflow/src/send/utils.ts]: @claude I don't think this can handle 18 decimal percision issue, please use bigInt instead

**Review by lmcmz — APPROVED** [review]
