### PR TITLE
fix: ui feedback - mobile

### LINKED ISSUE #244: [BUG] Issues found for ios 3.0.1 (1)
1. Circled component in screenshot are overlaping.

Image

2. Miss the close icon on the top of send page.

Image

3. When click the qr code icon, there is no response.

Image

4. The back arrow icon looks different with design.

Image

5. Missing of the bottom line.

Image

6. After I input the amount to send, the keyboard does not close. I think the keyboard should be dismissed when tapping outside of the keyboard area.

Image

7. Padding of bottom button is not correct, and the flow icon is missing.

Image

8. The closing icon is missing.

Image

9.After sending, we need to close send page.

https://github.com/user-attachments/assets/9c05901e-83cd-4310-8b1c-8d3d5fb5f042

### PR DESCRIPTION
**Pull request by lealobanov**
Closes #244

Closes #0917

### CODE REVIEW

File: apps/react-native/src/components/NavigationBackButton.tsx [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    <Pressable
+      style={({ pressed }) => [styles.button, pressed && styles.pressed]}
+      onPress={() => navigation.goBack()}
+    >
+      <BackArrowIcon size={24} color="#ffffff" opacity={0.8} />
+    </Pressable>
+  );
+};
+
+const styles = StyleSheet.create({
```
Comment (lmcmz) [inline apps/react-native/src/components/NavigationBackButton.tsx:37]: let's don't use stylesheet, keep using the same component as much as possible

File: apps/react-native/src/components/NavigationCloseButton.tsx [hunk 2]
```diff
@@ -0,0 +1,47 @@
+import React from 'react';
+import { Pressable, StyleSheet } from 'react-native';
+import Svg, { Path } from 'react-native-svg';
+
+import { platform } from '@/bridge/PlatformImpl';
+
+const CloseIcon: React.FC<{ size?: number; color?: string }> = ({
```
Comment (lmcmz) [inline apps/react-native/src/components/NavigationCloseButton.tsx:7]: Same for here

File: apps/react-native/src/assets/images/send_static.png
Comment (lmcmz) [inline apps/react-native/src/assets/images/send_static.png:1]: I think extension need this file as well, right? So why we don't put this image into our common packages?

File: apps/react-native/src/screens/SendScreenWrappers.tsx [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+
+// Create assets object
+const screenAssets: ScreenAssets = {
+  sendStaticImage,
+};
+
+// Wrapper components that pass the assets
+export const SendTokensScreen = () => <BaseSendTokensScreen assets={screenAssets} />;
+export const SendSingleNFTScreen = () => <BaseSendSingleNFTScreen assets={screenAssets} />;
+export const SendMultipleNFTsScreen = () => <BaseSendMultipleNFTsScreen assets={screenAssets} />;
```
Comment (lmcmz) [inline apps/react-native/src/screens/SendScreenWrappers.tsx:20]: This looks wired to me, there should be a better way to add image resource

File: packages/stores/src/profileStore.ts [hunk 4]
```diff
@@ -41,22 +41,40 @@ export const useProfileStore = create<ProfileStore>((set, get) => ({
...
         const walletProfilesData = await flow.getWalletProfiles();
+        console.log('📊 [ProfileStore] Wallet profiles data from bridge:', walletProfilesData);
 
         if (!Array.isArray(walletProfilesData.profiles)) {
           throw new Error('Invalid profiles data from bridge');
         }
 
         // Clean profile data
         const profiles: WalletProfile[] = walletProfilesData.profiles;
+        console.log('📊 [ProfileStore] Processed profiles:', {
```
Comment (lmcmz) [inline packages/stores/src/profileStore.ts:54]: please don't use console log.

File: packages/stores/src/walletStore.ts [hunk 5]
```diff
@@ -36,14 +36,26 @@ export const useWalletStore = create<WalletStore>((set, get) => ({
...
       const walletAccountsData = await flow.getWalletAccounts();
+      console.log('📊 [WalletStore] Wallet accounts data from bridge:', walletAccountsData);
 
       if (!Array.isArray(walletAccountsData.accounts)) {
         throw new Error('Invalid accounts data from bridge');
       }
 
       // Clean account data - only identity information
       const accounts: WalletAccount[] = walletAccountsData.accounts;
+      console.log('📊 [WalletStore] Processed accounts:', {
```
Comment (lmcmz) [inline packages/stores/src/walletStore.ts:49]: same here

File: packages/ui/src/components/ConfirmationDrawer.tsx [hunk 6]
```diff
@@ -182,7 +184,7 @@ export const ConfirmationDrawer: React.FC<ConfirmationDrawerProps> = ({
                   onPress={onClose}
                   cursor="pointer"
                 >
-                  <Close size={20} color="white" />
+                  <Close size={15} color="#ffffff" />
```
Comment (lmcmz) [inline packages/ui/src/components/ConfirmationDrawer.tsx:187]: It won't work for light mode

**Review by lmcmz — CHANGES_REQUESTED** [review]

File: apps/react-native/src/assets/images/send_static.png
Comment (lmcmz) [reply apps/react-native/src/assets/images/send_static.png:1]: Is there any reason why we didn't just put this image into package directly? We can force the extension use PNG as well

File: apps/react-native/src/components/NavigationBackButton.tsx [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+export const NavigationBackButton: React.FC = () => {
+  const navigation = useNavigation();
+  const theme = useTheme();
+
+  if (!navigation.canGoBack()) {
+    return null;
+  }
+
+  return (
+    <TouchableOpacity
```
Comment (lmcmz) [inline apps/react-native/src/components/NavigationBackButton.tsx:15]: We should have a IconButton on our UI packages, we should just import the IconButton or Button component in here. Instead of using react native raw component

File: packages/stores/src/walletStore.ts [hunk 8]
```diff
@@ -55,6 +55,7 @@ export const useWalletStore = create<WalletStore>((set, get) => ({
         error: null,
       });
     } catch (error) {
+      console.error('📊 [WalletStore] Error loading accounts:', error);
```
Comment (lmcmz) [inline packages/stores/src/walletStore.ts:58]: logger

File: packages/ui/src/components/ProfileList.tsx [hunk 9]
```diff
@@ -41,19 +41,20 @@ export function ProfileList({
       {profiles.map((profile, index) => {
         return (
           <React.Fragment key={profile.uid}>
-            <View height={0} width="100%" borderBottomWidth={1} borderBottomColor="$borderColor" />
+            {/* <View height={0} width="100%" borderBottomWidth={1} borderBottomColor="$borderColor" /> */}
```
Comment (lmcmz) [inline packages/ui/src/components/ProfileList.tsx:44]: Is it possible to [Tamagui List](https://tamagui.dev/ui/list-item) ? So we don't need worry about the styling and separator.
